#!/usr/bin/env bash

node index --oembed=https://www.notre-shop.com/collections/all.oembed --slack=BLAH
node index --oembed=https://oneness287.com/collections/all.oembed --slack=BLAH
node index --oembed=https://us.octobersveryown.com/collections/shop-all.oembed --slack=BLAH
node index --oembed=https://shop.exclucitylife.com/collections/footwear.oembed --slack=BLAH
node index --oembed=https://shop.exclucitylife.com/collections/new-arrivals.oembed --slack=BLAH
node index --oembed=https://cncpts.com/collections/all.oembed --slack=BLAH
node index --oembed=https://shop.bdgastore.com/collections/footwear.oembed --slack=BLAH
node index --oembed=https://shop.bdgastore.com/collections/new-arrivals.oembed --slack=BLAH
node index --oembed=https://rise45.com/collections/rise-new-arrivals.oembed --slack=BLAH
node index --oembed=https://rise45.com/collections/mens-footwear.oembed --slack=BLAH
node index --oembed=https://sneakerpolitics.com/collections/all.oembed --slack=BLAH
node index --oembed=https://shop.extrabutterny.com/collections/all.oembed --slack=BLAH
node index --oembed=https://kithnyc.com/collections/all.oembed --slack=BLAH
node index --oembed=https://rockcitykicks.com/collections/new-arrivals.oembed --slack=BLAH
node index --oembed=https://rockcitykicks.com/collections/sn.oembed --slack=BLAH
node index --oembed=https://shopnicekicks.com/collections/adidas.oembed --slack=BLAH
node index --oembed=https://www.deadstock.ca/collections/all.oembed --slack=BLAH
node index --oembed=https://packershoes.com/collections/new-arrivals.oembed --slack=BLAH
node index --oembed=https://packershoes.com/collections/footwear.oembed --slack=BLAH
node index --oembed=https://www.xhibition.co/collections/all.oembed --slack=BLAH
node index --oembed=https://beatniconline.com/collections/mens.oembed --slack=BLAH
node index --oembed=https://beatniconline.com/collections/frontpage.oembed --slack=BLAH
node index --oembed=https://www.saintalfred.com/collections/footwear.oembed --slack=BLAH
node index --oembed=https://www.saintalfred.com/collections/brands.oembed --slack=BLAH
node index --oembed=https://www.courtsidesneakers.com/collections/adidas-basketball.oembed --slack=BLAH
node index --oembed=https://www.bowsandarrowsberkeley.com/collections/all.oembed --slack=BLAH
node index --oembed=https://offthehook.ca/collections/fnf-product.oembed --slack=BLAH
node index --oembed=https://www.lapstoneandhammer.com/collections/all-products.oembed --slack=BLAH
node index --oembed=https://www.cityblueshop.com/collections/frontpage.oembed --slack=BLAH
node index --oembed=https://www.cityblueshop.com/collections/sneakers.oembed --slack=BLAH
node index --oembed=https://www.solestop.com/collections/footwear.oembed --slack=BLAH
node index --oembed=https://www.solestop.com/collections/frontpage.oembed --slack=BLAH
node index --oembed=https://www.featuresneakerboutique.com/collections/all.oembed --slack=BLAH
node index --oembed=https://www.12amrun.com/collections/footwear.oembed --slack=BLAH
node index --oembed=https://www.12amrun.com/collections/adidas.oembed --slack=BLAH
node index --oembed=https://wishatl.com/collections/all.oembed --slack=BLAH
node index --oembed=https://shoegallerymiami.com/collections/all.oembed --slack=BLAH
node index --oembed=https://www.bbbranded.com/collections/all.oembed --slack=BLAH
node index --oembed=https://burnrubbersneakers.com/collections/new-products.oembed --slack=BLAH
node index --atomfeed=https://noirfonce.eu/collections/all.atom --slack=BLAH
node index --atomfeed=https://suede-store.com/collections/all.atom --slack=BLAH
node index --atomfeed=https://www.addictmiami.com/collections/all.atom --slack=BLAH
node index --oembed=https://renarts.com/collections/all.oembed --slack=BLAH
node index --atomfeed=https://properlbc.com/collections/all.atom --slack=BLAH
node index --atomfeed=https://shop.exclucitylife.com/collections/all.atom --slack=BLAH
node index --atomfeed=https://nrml.ca/collections/all.atom --slack=BLAH
node index --oembed=https://www.socialstatuspgh.com/collections/all.oembed --slack=BLAH
node index --oembed=https://commonwealth-ftgg.com/collections/all.oembed --slack=BLAH
node index --oembed=https://centre214.com/collections/all.oembed --slack=BLAH
node index --atomfeed=https://www.oipolloi.com/collections/all.atom --slack=BLAH
node index --oembed=https://www.apbstore.com/collections/all.oembed --slack=BLAH
node index --oembed=https://nomadshop.net/collections/all.oembed --slack=BLAH
node index --atomfeed=https://vanrunco.com/collections/all.atom --slack=BLAH
node index --atomfeed=https://www.alumniofny.com/collections/all.atom --slack=BLAH
node index --atomfeed=https://atmosny.com/collections/all.atom --slack=BLAH
node index --atomfeed=https://www.huntinglodge.no/collections/all.atom --slack=BLAH
node index --oembed=https://www.marathonsports.com/collections/all.oembed --slack=BLAH
node index --oembed=https://www.urbanindustry.co.uk/collections/all.oembed --slack=BLAH
node index --atomfeed=https://www.westnyc.com/collections/all.atom --slack=BLAH
node index --atomfeed=https://samtabak.com/collections/all.atom --slack=BLAH
node index --atomfeed=https://thesportsedit.com/collections/all.atom --slack=BLAH
node index --atomfeed=https://www.uptownmia.com/collections/all.atom --slack=BLAH
node index --oembed=https://shop.havenshop.ca/collections/all.oembed --slack=BLAH
node index --atomfeed=https://shop.exclucitylife.com/collections/all.atom --slack=BLAH
node index --oembed=https://yeezysupply.com/collections/all.oembed --slack=BLAH
node index --oembed=https://shopnicekicks.com/collections/0-100.oembed --slack=BLAH
node index --oembed=https://shopnicekicks.com/collections/100-200.oembed --slack=BLAH
node index --oembed=https://shopnicekicks.com/collections/200-300.oembed --slack=BLAH
node index --oembed=https://shopnicekicks.com/collections/300-400.oembed --slack=BLAH
node index --oembed=https://shopnicekicks.com/collections/400-500.oembed --slack=BLAH
node index --oembed=https://shopnicekicks.com/collections/500.oembed --slack=BLAH
node index --oembed=https://us.bape.com/collections/footwear.oembed --slack=BLAH
